config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :news
  resources :events
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :contacts
      resources :news
      resources :events
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/new.rb
class New < ApplicationRecord
end

app/controllers/api/v1/news_controller.rb
module Api
      module V1
    class NewsController < ApplicationController
      before_action :set_news, only: [:show, :update, :destroy]
      before_action :authenticate_token


      # GET /news
      def index
        if @is_authenticated
          @news = New.where("created_at >= ?", 60.days.ago).order(publishedAt: :desc)

          render json: @news
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # GET /news/1
      def show
        if @is_authenticated
          render json: @news
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # POST /news
      def create
        if @is_authenticated
          @news = New.new(news_params)

          if @news.save
            render json: @news, status: :created, location: @news
          else
            render json: @news.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # PATCH/PUT /news/1
      def update
        if @is_authenticated
          if @news.update(news_params)
            render json: @news
          else
            render json: @news.errors, status: :unprocessable_entity
          end
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      # DELETE /news/1
      def destroy
        if @is_authenticated
          @news.destroy
        else
          render status: 403, json: {
            message: "No TOKEN auth."
          }.to_json
        end
      end

      private
        #This is to authenticate that the call is set from an account of the front-end
        def authenticate_token
          @is_authenticated = false
          if request.headers["TOKEN"]
            if request.headers["TOKEN"] == "AppDipre"
              @is_authenticated = true
            end
          end
        end
        # Use callbacks to share common setup or constraints between actions.
        def set_news
          @news = New.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def news_params
          params.require(:news).permit(:title, :description, :publishedAt, :source, :urlToImage, :url)
        end
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ActionController::Base
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = New.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = New.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'New was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'New was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_url, notice: 'New was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = New.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :description, :publishedAt, :source, :urlToImage, :url)
    end
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :publishedAt %>
    <%= form.date_select :publishedAt %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :urlToImage %>
    <%= form.text_field :urlToImage %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Publishedat</th>
      <th>Source</th>
      <th>Urltoimage</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.description %></td>
        <td><%= news.publishedAt %></td>
        <td><%= news.source %></td>
        <td><%= news.urlToImage %></td>
        <td><%= news.url %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>

<p>
  <strong>Publishedat:</strong>
  <%= @news.publishedAt %>
</p>

<p>
  <strong>Source:</strong>
  <%= @news.source %>
</p>

<p>
  <strong>Urltoimage:</strong>
  <%= @news.urlToImage %>
</p>

<p>
  <strong>Url:</strong>
  <%= @news.url %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_path %>